## How to get the common items between two python numpy arrays?

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [3]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [4]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [5]:
np.intersect1d(a,b)

array([2, 4])